syntax on
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
autocmd BufWritePre * :%s/\s\+$//e
colorscheme desert
filetype plugin on
highlight Pmenu guibg=DimGrey gui=bold
highlight SpecialKey ctermfg=DarkGray
imap <silent> <PageDown> <C-O>1000<C-D>
imap <silent> <PageUp> <C-O>1000<C-U>
map <silent> <PageDown> 1000<C-D>
map <silent> <PageUp> 1000<C-U>
map <C-t><down> :tabl<cr>
map <C-t><left> :tabp<cr>
map <C-t><right> :tabn<cr>
map <C-t><up> :tabr<cr>
map <F2> :make<CR>
map <F3> :make clean all<CR>
map <F4> :e %:p:s,.h$,.X123X,:s,.cpp$,.h,:s,.X123X$,.cpp,<CR>
map <F5> :!ctags -R –c++-kinds=+p –fields=+iaS –extra=+q .<CR>
set ai
set autoindent
set bg=dark
set comments=sl:/*,mb:\ *,elx:\ */
set cpoptions+=$
set enc=utf-8
set expandtab
set fenc=utf-8
set ignorecase
set list
set listchars=tab:>-
set listchars=tab:>-,trail:~
set listchars+=trail:.
set nocompatible
set nohlsearch
set number
set ruler
set shiftwidth=4
set showmatch
set smartcase
set smartindent
set smarttab
set tabstop=4
set t_Co=256
set termencoding=utf-8
set textwidth=120
set undodir=~/.vim/undodir
set undofile
set undolevels=1000
set undoreload=10000
set vb t_vb=
