#!/bin/bash
inst()
{
    echo "[+] installing $1"
    sudo apt-get -qq -y install $1
}

cd ~
echo "[+] updating repo"
sudo apt-get -qq -y update
inst make
inst python-mock
inst libc-dev
inst python-bs4
inst openssh-server
inst vim
sudo update-alternatives --config editor
inst gnome-session-fallback
inst git
inst mercurial
inst libxss1
inst python-pip
inst python-lxml
inst python-openssl
inst python-pyasn1
inst python-urwid
inst tmux
inst build-essential
inst irssi
inst ipython
inst python-beautifulsoup
inst python-mysqldb
inst qemu
inst sqlite3
inst nmap
inst unrar
inst libssl-dev
inst p7zip-full
inst htop
inst firefox
sudo pip -q install mitmproxy

# binwalk
echo "[+] installing binwalk"
git clone https://github.com/devttys0/binwalk
cd binwalk/src
sudo ./easy_install.sh > tmp
cd ~
sudo rm -r binwalk

# bowcaster
echo "[+] installing bowcaster"
git clone https://github.com/zcutlip/bowcaster
cd bowcaster
sudo python setup.py install > tmp
cd ~
sudo rm -r bowcaster

# john the ripper
echo "[+] installing john the ripper"
wget http://www.openwall.com/john/g/john-1.7.9-jumbo-7.tar.gz
tar -zxvf john-1*
rm john*.gz
cd john*/src
sudo make clean generic > tmp
cd ~
mv john*/run ~/tools/john
rm -r john*

# hashcat
echo "[+] installing hashcat"
wget http://hashcat.net/files/oclHashcat-1.01.7z
7z x oclHashcat*
rm ocl*.7z
mv oclHashcat* ~/tools/hashcat

# hashcat utils
echo "[+] installing hashcat utils"
wget http://hashcat.net/files/hashcat-utils-0.9-64.7z
7z x hashcat*
rm hashcat*.7z
mv hashcat* ~/tools/utils

# hashcat maskprocessor
echo "[+] installing maskprocessor"
wget http://hashcat.net/files/maskprocessor-0.69.7z
7z x maskp*
rm maskp*.7z
mv maskp* ~/tools/maskprocessor

rm tmp
