#!/bin/bash
inst()
{
    echo "[+] installing $1"
    sudo apt-get -qq -y install $1
}

cd ~
echo "[+] updating repo"
sudo apt-get -qq -y update
inst make
inst python-bs4
inst openssh-server
inst vim
sudo update-alternatives --config editor
inst git
inst tmux
inst build-essential
inst ipython
inst python-beautifulsoup
inst qemu
inst sqlite3
inst nmap
inst unrar
inst p7zip-full
inst htop
sudo pip -q install mitmproxy
inst terminator
